### ISSUE TITLE
select example request

### ISSUE THREAD

**Issue by dguisinger** [angular-redux/ng2-redux#194]
I have a request for an additional example on how to use select properly.  I'm using a normalizr style pattern.

If I have a state, that contains:
{
     items: Map<Number, Item>
     currentItemId: Number
}

What is the best way to use select to subscribe to both a change in currentItemId **and** any change that happens within that item in the map?

I've figured out how to monitor for the change in currentItemID, I subscribe to the observable in my component and then lookup the value and store it into my model when the current item id changes.  But that won't handle changes to the data inside the item.

**Comment by SethDavenport** [comment]
Is this an ES6 Map or an Immutable.Map?

**Comment by SethDavenport** [comment]
OK yeah just read up on normalizr a bit, looks like it's based on Immutable maps. Which is great. Let me cook up an example for you.

**Comment by SethDavenport** [comment]
Here you go: https://github.com/angular-redux/ng2-redux/pull/196

I was able to accomplish this with a selector function:

```typescript
import { Component } from '@angular/core';
import { NgRedux, select } from 'ng2-redux';
import { Observable } from 'rxjs/Observable';
import { ItemMapActions } from '../actions/item-map.actions';

@Component({
  selector: 'item-map-display',
  providers: [ ItemMapActions ],
  template: `
    <h3>Current Item</h3>
    <pre>{{ currentItem$ | async | json }}</pre>
    <button (click)="actions.setCurrentItem('1')">Set currentItemId to 1</button>
    <button (click)="actions.setCurrentItem('0')">Set currentItemId to 0</button><br>

    <button (click)="actions.updateItemName('0', 'wat')">
      Rename Item 0 to 'wat'
    </button>
  `
})
export class ItemMapDisplay {
  @select(currentItem) currentItem$: Observable<Object>;

  constructor(private actions: ItemMapActions) {}
}

function currentItem(state) {
  return state.itemMap.items.get(state.itemMap.currentItemId);
}
```

And here are the actions that actually update the store:

```typescript
import { Injectable } from '@angular/core';
import { NgRedux } from 'ng2-redux';

@Injectable()
export class ItemMapActions {
  static SET_CURRENT_ITEM = 'SET_CURRENT_ITEM';
  static UPDATE_ITEM_NAME = 'UPDATE_ITEM_NAME';

  constructor(private ngRedux: NgRedux<any>) {}

  setCurrentItem(itemId: Number) {
    this.ngRedux.dispatch({
      type: 'SET_CURRENT_ITEM',
      payload: itemId,
    });
  }

  updateItemName(itemId: string, name: string) {
    this.ngRedux.dispatch({
      type: 'UPDATE_ITEM_NAME',
      payload: {
        itemId,
        name,
      },
    });
  }
}
```

**Comment by dguisinger** [comment]
That was fast!  Thank you :)

**Comment by Vespira** [comment]
Hi man, thanks for code snippet 👍 , I was wondering how to watch for a specific Map item if a Map was stored into my state ? 

My state sample : 
export interface SaleStateInterface {
  // baskets containing product details : <id, array<products>>
  baskets: Map<string, Array<ProductDetails>>;
}

And I try to get the current basket from it's ID directly in select with these kind of (not working) codes : 

1 - 
export const getCurrentBasket = obs$ => obs$
  .filter((basket, index) => index === 'static_uuid')
  .map(basket => basket);

@select$(['myState', 'baskets'], getCurrentBasket)
readonly basket$: Observable<Map<string, Array<ProductDetails>>>;

2 - 
@select(store => store.myState.baskets.get(store.myState.currentBasketUuid))
readonly basket$: Observable<Map<string, Array<ProductDetails>>>;

3- 
@select(['myState', 'baskets', 'static_uuid'])
readonly basket$: Observable<Map<string, Array<ProductDetails>>>;

None of these is working, I got in the first case an error because .filter() is not a function (on null value I guess),in the second case an empty object (as my initial state is defined), and in the third case I doens(t do anything and I have still an empty object when I subscribe to this Observable :(

Any suggestion on how to do this properly ? thx
