### ISSUE TITLE
Need to unsubscribe?

### ISSUE THREAD

**Issue by brianchance** [angular-redux/ng2-redux#195]
Not an issue, just a question.

Since the store is long running, is it best practice to unsubscribe to any subscriptions created during a components load?

I have an instance where I call a component method in the subscribe callback that blows and it fires even after navigating to another page. Unsubscribing fixed the issue, made me wonder about all the other subscriptions.

I know I could use @select, but it gets tedious with properties on the object (i.e. `
{{(cart | async).amountDue | currency}}` and I need the values in the component code.

**Comment by SethDavenport** [comment]
Hi @brianchance,

Yes in cases where you subscribe, it's worth thinking about whether the component in question is one that will get mounted and unmounted from the DOM over the course of the app's life time. If so, I would recommend unsubscribe or you may end up with odd behaviour after the component is unmounted.

I do favour `@select` and async pipe as much as possible, since async pipe handles unsubscribe in for you. To that end we've tried hard to make `@select` as flexible as possible: for your example have you considered something like:

```typescript
@select(['cart', 'amountDue']) amountDue$
@select(['cart', 'someOtherProp']) someOtherProp$
```

instead?

Ultimately it's a matter of taste though.

**Comment by brianchance** [comment]
@SethDavenport - thank you, will try some other variations with async pipe.
