### ISSUE TITLE
Problems with setIn...

### ISSUE THREAD

**Issue by windischb** [angular-redux/ng2-redux#246]
Hi!

I'll have problems to set a property with a new value...

My state looks like this:
```
export interface ISettings {
    SignalR: {
        connect: boolean
    }
}

export interface IAppState {
    Settings?: settings.ISettings;
}
```

and in my Reducer i want to set the Property "connect" in to true
`return state.setIn(["SignalR","connect"], value)`

All i'll get is an Error wich says:
"invalid keyPath at invariant"

Whats wrong???

**Comment by SethDavenport** [comment]
Looks like there's something funky with the way you're using ImmutableJS - can you post the code of your reducer?

**Comment by windischb** [comment]
I'll create the reducer in the same Example as in #244...
Thanks!

**Comment by SethDavenport** [comment]
@windischb I downloaded and ran the front-end portion of the example and I can't reproduce the error.

I wasn't running the backend because I'm not equipped to run C# on this machine. But hitting the 'not working' buttons succeeds in updating `state.SignalR.connect` properly in my store.

Random guess - can you try an `rm -rf node_modules; npm cache clean; npm install` just to rule out any package dependency issues?

**Comment by windischb** [comment]
Hmm... Thats strange....
The Error only occures if you hit the "not working" button at first. No other button before or reload the Page.
I'll test your proposal as soon as possible!

**Comment by SethDavenport** [comment]
OK yeah I can repo now. Sorry I missed that detail

**Comment by SethDavenport** [comment]
See my comment on #244
