### ISSUE TITLE
How to update state?

### ISSUE THREAD

**Issue by Redigast13** [angular-redux/ng2-redux#258]
I use [angular2-hmr](https://github.com/AngularClass/angular2-hmr) module and I need to update state if developer changes any file in the project. I created two methods in AppModule: `hmrOnInit()` and `hmrOnDestroy()`
If developer changes any file, then hmrOnDestroy is called. I save current state in this method ( `let state = this.redux.getState()` ). Then hmrOnInit is called, I should update current state in this method. How to do it?

**Comment by SethDavenport** [comment]
Hmm looks like you need to allow a way to 'sideload' the state somehow. Would a custom action (e.g. INIT_STORE) work or does that cause issues when called as part of the HMR init?

**Comment by SethDavenport** [comment]
Cool to see an NG2 HMR solution though, certainly would like to make it easy to use with ng2-redux.

**Comment by Redigast13** [comment]
@SethDavenport custom action works, but I have many reducers that are combined with `combineReducers()` function:

// root reducer
```
combineReducers<IAppState>({
	reducer1,
	reducer2,
	reducer3
})
```
And I would not like to change each reducer for adding INIT_STORE event handler. But if there is no method to update state directly I will have to use custom action

**Comment by SethDavenport** [comment]
Oh right.

Well we do expose the `store.replaceReducer` function used for hot loading in the React world: https://github.com/erikras/react-redux-universal-hot-example/issues/44#issuecomment-132260397

**Comment by gviligvili** [comment]
Just searched for it too, would be glad for a nicer solution :), 
is there anything new?

**Comment by SethDavenport** [comment]
Only what I said before - hot loading in the redux world uses replaceReducer, which we already expose. It should be possible to do the same thing.

**Comment by gviligvili** [comment]
Well, excuse me, I'm new to this.
But reducers suppose to be the pure function which handle data manipulations ,

Lets say my state is : { counter : 6 }
how does replacing my reducers to suppose to help?
- even if they do change the state, it becomes to 0 because it's a new reducer. isn't it? so I didn't really achieved anything. 

I'm really confused.
Sorry for my english.

**Comment by SethDavenport** [comment]
Sorry @gviligvili, I'm not an expert in HMR either. My comment was simply to say that whatever magic makes it work in a react-redux project should also be possible in an Angular one.  I haven't had time to really study what either HMR loader is actually doing in detail.

**Comment by SethDavenport** [comment]
What they seem to be doing is persisting state and rehydrating it from local storage (the persistState does that for them under the hood when the store is reconstructed with replaceReducer); I agree now that I look at it that it seems kind of weird. I'll see if we can expose something better.

**Comment by gviligvili** [comment]
Yeah, That's what i've been using right now too.
Here's a scenario, Our project suppose to have a lot of entities schema, so I would like to use Record types.
but because the store is being serialize and deserialize, with each HMR , I'm required to deserialize the entities back to records.
not all my entities are records and that what makes it so much hard to maintain. (need to cherry pick my entities, and give them a special treatment in my deserialize function).

**Comment by SethDavenport** [comment]
Redux doesn't expose anything like this directly, which makes it tricky for us to do it.

However you can probably do something more clever with replace reducer:

```
// restoring after a hot reload:
ngRedux.replaceReducer(() => savedState); // Trivial reducer that just returns the saved state.
ngRedux.dispatch({ type: 'REHYDRATE' })     // Bogus action to trigger the reducer above.
ngRedux.replaceReducer(yourAppsRootReducer); // Put the real version of the reducers back.
```

That last line will also make sure that any code changes to your app's reducers gets applied to redux going forward as well.
