### ISSUE TITLE
Question about redux and angular2

### ISSUE THREAD

**Issue by gnujeremie** [angular-redux/ng2-redux#266]
Hi,

I'm not submitting a bug report, I'm just looking for some explanations, and want to be sure I understand correctly the way angular 2 and redux work together.

When the reducer returns the new state, this is a completly new object. So, in my angular components, every @select() is "triggered" right ? 

In my case, I have a pretty complex state looking more or less like this : 
```
{
    dasboard: {
        users: {
             123456AB: {...},
             123456AC: {...},
             123456AD: {...},
        },
        vectors: {
             123456AE: {...},
             123456AF: {...},
        },
        ...
    }
}
```

In one component, i have 
```
@select(['dashboard', 'users']) users$: Observable<any>;
...

ngOnInit() {
    this.subUsers = this.users$.subscribe((users) => {
         // blablabla
    })
}
``` 
and in another one i have 

```
@select(['dashboard', 'vectors']) vectors$: Observable<any>;
...
ngOnInit() {
    this.subVectors = this.vectors$.subscribe((vectors) => {
         // blablabla
    })
}
```

And in my templates I have something like

```
<ul>
    <li *ngFor="let user of users$ | async | keys">{{ user.name }}</li>
</ul>
```
(keys is a pipe I created so I could loop over an object)

Suppose I update ```dashboard.vectors.123456AE```. My reducer returns a new state, because at the begin I copy the state this way : ```let copyState = JSON.parse(JSON.stringify(state))``` in order to work on a new object.
All my components are rendered again, even the one linked only to the users part, and even if the users properties did not change. Is it right, or am I doing something wrong ? I'm not sure about the perf, because my whole application is refreshed even when it should not be.

Thanks a lot !

**Comment by alinnert** [comment]
Hi @gnujeremie 

I'm not sure why all components get re-rendered. My guess is: the check works "per store object". In this case "dashboard" (it is dashboard, not dasboard, right?). Normally you don't group data in the store by view (or anything else) but make the kind of data you're dealing with the root properties. Like this:

~~~javascript
{
  users: {
    list: [ { /* Normally arrays are better because they have an order you can rely on. */ } ],
    loading: false // normally I use a flag here to indicate whether the list is loading. This way it's very easy to implement loading indicators.
  },
  vectors: { /* ... */ }
}
~~~

But I can tell you that `JSON.parse(JSON.stringify(state))` is slow. A better approach could be this:

~~~javascript
const newState = Object.assign({}, oldState, {changedProperty: changedValue});
~~~

Alternatively you can use a library that makes working with objects and arrays easier without modifying them - example: [Ramda](http://ramdajs.com/) (But it's not yet nice to use with ES6 `import`). Or you can use libraries like [Immutable.js](https://facebook.github.io/immutable-js/).

**Comment by gnujeremie** [comment]
Thanks for you answer. I was planning to change my store so I would have something like your advice
```
{
    users: {...},
    vectors: {...}
}
```

Thanks again :)

**Comment by spock123** [comment]
Just a comment: do you remember to unsubscribe in the ngOnDestroy methods?

**Comment by SethDavenport** [comment]
Another comment - if you're using `| async`, you don't need to also subscribe in `ngOnInit`: `async` will manage the subscription for you.

As for refresh - `@select` (and the non-decoration version, `ngRedux.select`) both use the [distinctUntilChange](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/distinctuntilchanged.md) operator under the hood to cut down on updates when that selector's input data hasn't changed.  So the users stuff should not be firing if only the vectors stuff changed, and vice versa.  It's possible that your JSON serialize/deserialize approach is doing something odd; I second @alinnert 's comment about `Object.assign` or Ramda instead (Ramda is a great lib).

However if you want to dig into it a little more, `@select` also allows you to specify a custom comparator that it will determine if the selector's data really changed:

```typescript
function usersComparator(old, new) {
  // Custom comparator logic: stick a debugger in here to see what's going on?
  return old === new; // This is what the default check does.
}

@select([ 'dashboard', 'users' ], usersComparator);
```

Finally, depending on what your `keys` pipe does, you may be running into `ngFor` oddness that happens when it's given a new array instance each time it loops.  Can you post the code for 'keys'?

**Comment by gnujeremie** [comment]
@spock123 yes, i unsubscribe in ngOnDestroy :)

@SethDavenport thanks for your explanations. I know ```@select``` does the unsubscribe, however I do need to subscribe in my component, for other operations on the data from the state.

I'll dig into Ramda, and for know I started using several reducers (one for users, one for vectors) and it seems to fix most of my problems.

Thanks to all of you for your help and explanations !
