### ISSUE TITLE
select fires on unrelated component changes

### ISSUE THREAD

**Issue by sgantrim** [angular-redux/ng2-redux#280]
I have a component that uses both redux store values as well as local values that are not in my redux store. Any changes made to the local value causes any and all @select statements that use the function method to fire, leading to performance issues. Is this a bug, or a feature that I can turn off?

![image](https://cloud.githubusercontent.com/assets/11021014/20895915/13a11804-bae1-11e6-96f4-d0c6a84d68c7.png)

**Comment by danielfigueiredo** [comment]
I think that is expected to happen with angular, because your view changed when your foo variable receives a different input. That will trigger ```detectChangesInternal``` that will force the async pipe to ```transform``` again, thereafter executing the selector function again. In my test it fires twice since angular calls transform from async pipe (related to your observable twice) for every character you input.
Regardless of the Change Detection Strategy I got the same results, if you're processing a lot maybe you can use a comparor function =]

**Comment by e-schultz** [comment]
@sgantrim one thing to keep in mind when using `@select` - if you return a new object out of it, it will always be considered 'new' - and all of the downstream subscribers will be hit.

for example.
lets assume you want the person object to also have the address
and the address is stored in another part of the state, and you can look it
up by an ID.

```js
class SomeComponent {
  
  @select(state => {
    return {
      id: state.contact.id
      firstName: state.contact.firstName,
      lastName: state.contact.lastName,
      city: state.address.find(n => n.contatId === state.person.id).city
    }
  }) person$;

  ngOnInit() {
    this.person$.subscribe(n => {
      console.log('the person has updated', n);
    });
  }
};
```
  
This will be called /every/ time there is an update in the state,  even if nothing on person or address has updated.

select will do a 'distinctUntilChanged()' - however, you are returning a new object every time, and the default behavior is to check by object reference.

Since you are returning a new object every time it runs - anything that is subscribed to it will get a new value.      

If you are wanting to do more complex `selectors` that are doing calculations / combining data / etc, there are a few ways of doing this.

One way - is using the [reselect](https://github.com/reactjs/reselect) library, and having your reselect selectors be the functions you pass into `@select`

```js
// this is from their docs

import { createSelector } from 'reselect'

const shopItemsSelector = state => state.shop.items
const taxPercentSelector = state => state.shop.taxPercent

const subtotalSelector = createSelector(
  shopItemsSelector,
  items => items.reduce((acc, item) => acc + item.value, 0)
)

const taxSelector = createSelector(
  subtotalSelector,
  taxPercentSelector,
  (subtotal, taxPercent) => subtotal * (taxPercent / 100)
)

export const totalSelector = createSelector(
  subtotalSelector,
  taxSelector,
  (subtotal, tax) => ({ total: subtotal + tax })
)

let exampleState = {
  shop: {
    taxPercent: 8,
    items: [
      { name: 'apple', value: 1.20 },
      { name: 'orange', value: 0.95 },
    ]
  }
}

// and use with ng2-redux....

class SomeComponent {
  @select(totalSelector) total$;
}
```

Reselect will take care of the memoization / etc for you. 

Another approach, is changing how you pull out / derive the data. 

```js

class SomeComponent {
  @select(state=>state.contact) contact$; 
  @select(state=>state.addresses) addresses$;
  person$ = this.contact$
  .combineWithLatest(this.address$,(contact, address) => {
    return {
      firstName: contact.firstName,
      lastName: contact.lastName,
      city: addresses.find(n => n.contatId === state.person.id).city
    }
  });

  ngOnInit() {
    this.person$.subscribe(n=>{
       console.log('the person has updated', n);
    })
  }
  
}

```

Now the `person$.subscribe` should only be called if the contact or the address parts of state have updated. Every time the redux store updates - if it hasn't touched `stat.contact` or `state.addresses` - that will be returning the same object reference, so the subscribers won't be notified.

However, if there is a chagne in either of those properties - then the subscription gets hit, and when you expected it to.

Alternativly, you can provide a custom comparor function as a second argument to `@select`


```js
class SomeComponent {
  
  @select(state => {
    return {
      id: state.contact.id
      firstName: state.contact.firstName,
      lastName: state.contact.lastName,
      city: state.address.find(n => n.contatId === state.person.id).city
    }
  },(a,b)=>{
    // better ways of doing this, just an example ....
    // for a flat object, could use some sort of shallow equal 

    return a.id === b.id && 
      a.firstName === b.firstName &&
      a.lastName === b.lastName &&
      a.city === b.city
  }) person$;

  ngOnInit() {
    this.person$.subscribe(n => {
      console.log('the person has updated', n);
    });
  }
};
```

In which case - even though you are always returning a new object out of the select, your compare function is saying 'hey, this is the same' - and the subscription will only get hit if the values actually do change.

Hope this helps, let me know if you have any other questions.

**Comment by sgantrim** [comment]
With all due respect to the detailed answers and code samples provided, I believe this is still a problem. It is my understanding that unless an action has been dispatched to the store, we are assured that the state tree has not changed. Put another way, the **only** way to affect state is by dispatching an action to the redux store. The example I provided shows that changes to a local component variable that:

1. has nothing to do with the state tree, and
2. does not dispatch an action to the store

still causes any and all ng2-redux @select functions to re-evaluate if they use the ((state: IAppState) => ...) option. Since typing a character in an input box that is data-bound to a local string variable does not dispatch an action, it is quite troubling that potentially expensive @selects fire with each keystroke.
