### ISSUE TITLE
Share store between client and server sides

### ISSUE THREAD

**Issue by templth** [angular-redux/ng2-redux#298]
Hi,

I'm using ng2-redux successfully in my project. Really great tool! My project uses server rendering with Angular Universal and now I'm trying to share the store between the two sides.

Is there a way to handle this with ng2-redux?

Thanks for your help!

**Comment by SethDavenport** [comment]
I haven't had the chance to play with Universal, but I have written isomorphic react-redux so I imagine the approach would be similar. In which case, with ng2-redux I would handle it more or less as follows:

On the server side, just before you're ready to send back the rendered HTML, inject the output of `ngRedux.getState()` as JSON somewhere into your DOM. Don't forget to escape the JSON to avoid XSS attacks (e.g. with https://github.com/yahoo/serialize-javascript or similar).

Then when the app loads in the browser, grab that state and use it as the `initialState` parameter for  `ngRedux.configureStore` or `ngRedux.provideStore`.

**Comment by templth** [comment]
@SethDavenport thanks very much, Seth, for your answer! My problem was: how to get an instance of `ngRedux` on the server? I also played with react / redux within isomorphic applications. In this case, I had an instance of the store... See what I mean?

In the case of Angular2, the `ngRedux` is a property of a component...

**Comment by SethDavenport** [comment]
ngRedux is only a property of the component because it's dependency injected. The actual ngRedux instance is a singleton.

what I would suggest is use `ngRedux.provideStore` instead of `ngReduc.configureStore` in your app component.  That way you can make your redux store using vanilla redux methods and `attach` is to ngRedux during bootstrap.

This should give you the flexibility to initialize the store differently on the client side and the server side.

Does this help?
