### ISSUE TITLE
selector executed more then should be

### ISSUE THREAD

**Issue by olaf89** [angular-redux/ng2-redux#309]
In my example my selector is performing quite expensive computation, when state is not changing i would not expect it to be executed, but currently it is. In my project i have actions that are often not changing state, each time every selector is called.
It works as expected when i do this.store.select().map(selector).

**Comment by olaf89** [comment]
I dont know how to contribute, but maybe fix could be something like :
```
        if (typeof selector === 'string' ||
            typeof selector === 'number' ||
            typeof selector === 'symbol') {

            resultFn = state => state[selector as PropertySelector];
        } else if (Array.isArray(selector)) {
            resultFn =state => getIn(state, selector as PathSelector);
        } else {
            result = selector as FunctionSelector<RootState, S>;
        }

        return this._store$.distinctUntilChanged(selector , comparator);
```

**Comment by kfurmann** [comment]
Yes, `@select` seems to cause Angular's change detection even if there was no apparent change of values bound to the components. I think ngOnChanges is executed because the `@select` getter always returns a new Observable. Angular notices the new reference in `@Input` and reacts, even though the current value of the Observable sequence is the same as the previous value.

https://github.com/angular-redux/ng2-redux/blob/master/src/decorators/select.ts#L35
https://github.com/angular-redux/ng2-redux/blob/master/src/components/ng-redux.ts#L155

I've forked an example from ng2-redux docs:
https://plnkr.co/edit/nkkv1QExp3S76wf6UgTc?p=preview

See in the console how ngOnChanges is executed 4 times (2 for each sibling component) after a single state change was made by clicking on + or -.

Is this a desired behavior? Am I using ng2-redux in a correct way?

**Comment by olaf89** [comment]
You are doing it incorrecly:
1. you should not be passing streams to child component but values
2. in your container you should not be using onPush change detection since its not changing after its inputs are chaning
Both things are connected to angular change detection so you might want read more about that.

here is updated plunker:
https://plnkr.co/edit/ANqARUaewCDUYGlI80Jw?p=preview

**Comment by e-schultz** [comment]
You know, going to look into this a little bit more, forked the fork [here](https://plnkr.co/edit/vEa9b3Cz32r9FtFhxvpG?p=preview)

if doing `counter$ = this.redux.select('counter')` instead of `@select()`  - you'll see things behave that you were expecting. 

That said - if you are needing to do complex transformations within your selector - if your select is always returning a 'new' object - it will always trigger CD, and you might want to look into using [reselect](https://github.com/reactjs/reselect) to pass into your selectors, or - have selects that point to a location in the state, then use something like `combineWithLatest` to do the transformations - so the transformations only operate when parts of the state change that you care about.

In terms of ngOnChanges getting triggered, I'd expect `@select` and `redux.select` to behave in the same way.

**Comment by olaf89** [comment]
Well, im sorry but im not convinced, i agree that in your one use case you're totally right, it does not matter but im sure this library is used in many different projects with varying use cases. In my opinion there is no point of running selectors when state did not change, and in my case its quite harmful, if you think that this is so rare case that change would be not beneficial for library then fine, i understand ill have it in different way.

**Comment by e-schultz** [comment]
Hi,

I think you misunderstood - and this is something I am looking into, and have a potential fix - and a PR for it.

What I was trying to clarify though,  is if the result of your `select` is a new object every time, then it will have the potential to trigger change detection - even if the parts of the state that the select statement cares about have not changed. 

```ts
@select(state=>{ 
    return { person: { fullName: `${state.firstName } ${state.lastName}` } };
}) personWithfullName$;
```

Even if `firstName` and `lastName` don't change - but other parts of the state do, components that you are passing this value into - even if using `OnPush` will have their CD triggered because it's getting a new object every time.

If you wanted CD in the component that you are passing into to only fire if the values of firstName and lastName got changed, you might do something like:

```js
@select((state)=>state.firstName) firstName$
@select(state)=>state.lastName) lastName$;
personWithfulllName$ = firstName$.combineWithLatest(this.lastName$,(firstName,lastName)=> {
   return { person: { fullName: `${firstName} {lastName}` } }
});
```

Then only when firstName or lastName changes - then the heavy lifting happen.

If you are doing heavy lifting in your select statements, and want to ensure that they are only run when the parts of state they care about change - then reselect, or changing how you combine data may be worth looking into.

The issue you are describing if I understand correctly:

Select functions are are called even if the state has /not/ changed. 

For example - an action gets dispatched, no reducers handle it, so state remains constant - select fires regardless. 

Was able to reproduce the issue you are describing though, and have PR #310 open with a potential fix - which is close to what you were suggesting the other day.

When working with ng-redux and/or the connect/mapStateToTarget pattern (which is/soon to be) deprecated in ng2-redux - we were doing a shallow equal before calling the function passed into mapStateToTarget.

Thanks for bringing this up, and if this fix goes into the current major version - should be easy enough to back-fill into previous major versions as a patch/fix.

**Comment by olaf89** [comment]
Hi, great to hear that, your understanding about my issue is fully correct. PR looks good, waiting for it to be merged. Thanks!

**Comment by e-schultz** [comment]
@olaf89 sorry for the delay in the publish - new version is out now, please let me know if you have any other issues. Cheers.
