### ISSUE TITLE
Integration with Angular2 Seed

### ISSUE THREAD

**Issue by nareshbhatia** [angular-redux/ng2-redux#31]
Could you please provide some guidance to integrate ng2-redux with [angular2-seed](https://github.com/mgechev/angular2-seed). My first question is how to initialize ng2-redux in the angular2-seed's [AppComponent](https://github.com/mgechev/angular2-seed/blob/master/src/app/components/app.component.ts) instead of `bootstrap()`? In angular2-seed, `bootstrap()` is not as accessible.

**Comment by nareshbhatia** [comment]
Is this the appropriate place to ask this question? Happy to take it somewhere else if more appropriate.

**Comment by wbuchwalter** [comment]
Hey Narash,


I'm currently on a trip, so didn't had time to take a look at your issue!

Will try to do so soon.

Might be a good idea to duplicate your issue on angular-seed too.


Thanks




From: Naresh Bhatia

Sent: Friday, April 15, 1:57 PM

Subject: Re: [wbuchwalter/ng2-redux] Integration with Angular2 Seed (#31)

To: wbuchwalter/ng2-redux



Is this the appropriate place to ask this question? Happy to take it somewhere else if more appropriate.

**Comment by nareshbhatia** [comment]
Good idea - I will create an issue on angular2-seed too.

**Comment by nareshbhatia** [comment]
I have [an issue](https://github.com/mgechev/angular2-seed/issues/769) logged for this on angular2-seed. More importantly, I created a new project that combines angular2-seed + ng2-redux: https://github.com/archfirst/angular2-seed-redux. I had to install bunch of type definitions that I did not see in the README steps here. Anyway, I am currently stuck on a very basic error:

```
src/client/main.ts(7,25): error TS2307: Cannot find module 'ng2-redux'.
```

I can't figure this one out. I have installed the ng2-redux package and it exists in my node_modules folder. So I can't understand why the compiler doesn't find it.

I would really appreciate if someone on this group can help me get this combination working. Thanks in advance for all your help.

**Comment by wbuchwalter** [comment]
Hey Naresh,
Typings for `ng2-redux` is currently a work in progress.
Everything is being rewritten directly in TypeScript ([here](https://github.com/wbuchwalter/ng2-redux/tree/typescript)).
I think @e-schultz and @bennett000 are going to release a beta on npm very soon.

**Comment by bennett000** [comment]
@nareshbhatia `src/client/main.ts(7,25): error TS2307: Cannot find module 'ng2-redux'` my guess is that this module is not being found (by `tsc`) because it lacks typings.  

- One solution to this would be to use a library like `typings` to install `ng2-redux` typings from a source like Definitely typed.

- Another solution would be to use the beta version of `ng2-redux` which can be installed with a command like `npm install --save-dev ng2-redux@beta`.  

Additionally you can take a [look at this starter](https://github.com/rangle/angular2-redux-starter "Rangle's ng2-redux-starter") which uses ng2-redux and Angular 2 to assemble a minimal "starter" application.

**Comment by SethDavenport** [comment]
@nareshbhatia: we just released version 2.2.3 which has been rewritten in typescript and thus includes typings.  That should resolve your TS2307 error at least.

Can you give it a try?

**Comment by nareshbhatia** [comment]
Thanks @SethDavenport. The TS2307 is gone. However, I am getting the following errors now.

```
/Users/nbhati/projects/angular2-seed-redux/node_modules/ng2-redux/lib/components/ng-redux.d.ts(13,24): error TS2315: Type 'Store' is not generic.
/Users/nbhati/projects/angular2-seed-redux/node_modules/ng2-redux/lib/components/ng-redux.d.ts(20,34): error TS2315: Type 'Store' is not generic.
/Users/nbhati/projects/angular2-seed-redux/node_modules/ng2-redux/lib/components/ng-redux.d.ts(30,54): error TS2315: Type 'Dispatch' is not generic.
/Users/nbhati/projects/angular2-seed-redux/node_modules/ng2-redux/lib/components/ng-redux.d.ts(30,78): error TS2315: Type 'ActionCreator' is not generic.
/Users/nbhati/projects/angular2-seed-redux/node_modules/ng2-redux/lib/components/ng-redux.d.ts(30,110): error TS2305: Module 'Redux' has no exported member 'ActionCreatorsMapObject'.
/Users/nbhati/projects/angular2-seed-redux/node_modules/ng2-redux/lib/components/ng-redux.d.ts(44,90): error TS2305: Module 'Redux' has no exported member 'Unsubscribe'.
/Users/nbhati/projects/angular2-seed-redux/node_modules/ng2-redux/lib/components/ng-redux.d.ts(56,48): error TS2305: Module 'Redux' has no exported member 'Unsubscribe'.
/Users/nbhati/projects/angular2-seed-redux/node_modules/ng2-redux/lib/components/ng-redux.d.ts(66,52): error TS2305: Module 'Redux' has no exported member 'Action'.
/Users/nbhati/projects/angular2-seed-redux/node_modules/ng2-redux/lib/components/ng-redux.d.ts(70,32): error TS2305: Module 'Redux' has no exported member 'Action'.
/Users/nbhati/projects/angular2-seed-redux/node_modules/ng2-redux/lib/components/provider.d.ts(3,44): error TS2315: Type 'Store' is not generic.
```

You should be able to reproduce them on my project: https://github.com/archfirst/angular2-seed-redux

**Comment by SethDavenport** [comment]
Hi @nareshbhatia I took a look at your repo - it looks like you're using the redux typings from definitely typed. Redux 3.4 now ships with its own official typings in npm.

Let me suggest a few minor changes to your seed:

__Change 1:__ In your `typings.json` you need to remove the entry for Redux.  Then do

```sh
rm -rf typings; typings install
``` 

This will let typescript pull in the correct typings from your `node_modules`.

__Change 2:__

The official redux typings require an initial state in `createStoreWithMiddleware`.  So in your `main.ts`, online 13, I suggest something like: 

`const store = createStoreWithMiddleware(rootReducer, {});`

__Change 3__:

Finally, the redux-thunk typings are very out-of-date in definitelytyped, and don't play well with the official redux typings.  Hopefully me or someone else will have time to make a PR against redux-think for correct typings.

For now in my project I use redux-thunk in untyped form: instead of `import`-ing it, I do:

`const thunk = require('redux-thunk').default;`

Hope, this helps,
Seth

**Comment by nareshbhatia** [comment]
Thanks @SethDavenport. That fixes all the compile errors.

**Comment by SethDavenport** [comment]
Happy to help.
