### ISSUE TITLE
Component unit test complains about missing provider for ngRedux

### ISSUE THREAD

**Issue by TobiasKrogh** [angular-redux/ng2-redux#51]
Hi,

I am fairly new to Angular 2 and ng2-redux so I want to apologize upfront if I just oversaw a small thing. I have a small Angular 2 app and recently integrated ng2-redux which worked like a charm. So mapping of state and dispatch works as expected and I basically followed the README step by step and the store changes are perfectly reflected. 👍 

I started creating a spec (based on Jasmine) for the app component I connected via ng2-redux and executing the tests via Karma are running into the following issue:

```
Failed: No provider for ngRedux! (App -> ngRedux)
```

I tried several things and also tried to find my way through a lot of documentation but can't seem to find the right solution. From what I understand I need to pass either a proper implementation or mock here:

```javascript
// provide our implementations or mocks to the dependency injector
beforeEachProviders(() => [
  App
]);
```

I tried duplicating the conditions for the main bootstrap but when I do so (or any other way) there is an error occurring at _instantiateProvider in the injector.ts of angular 2 (no specific error message though). Am I missing something? Can you help me or is this the wrong place to ask this question? I found nearly no documentation about adding a provider for the ngRedux factory or factories in general (hope I use the proper wording here).

Thanks and regards,
Tobias

**Comment by SethDavenport** [comment]
Hi @TobiasKrogh ,

Thanks for your interest in ng2-redux!

Can you post the code for your test? It would help to see what approach to testing you're trying.

**Comment by TobiasKrogh** [comment]
Hi @SethDavenport,

thanks for the quick reaction. The test looks like this:

```javascript
import {
  it,
  inject,
  injectAsync,
  beforeEachProviders
} from 'angular2/testing';

import { ApplicationRef } from 'angular2/core';

import { App } from './app.component';

describe('App', () => {
  // provide our implementations or mocks to the dependency injector
  beforeEachProviders(() => [
    ApplicationRef,
    App
  ]);

  it('should have a name', inject([ App ], (app) => {
    expect(app.name).toEqual('Hello App');
  }));

});
```

Upon removing the connection to the store from the app.component this test passes.

**Comment by TobiasKrogh** [comment]
@SethDavenport I do not know whether this is important: I am using webpack as a module bundler.

I updated and tested this with `ng2-redux` 2.2.3 as well. I cannot use the syntax mentioned in the README:
`import { provider } from 'ng2-redux';` respectively `import { NgRedux } from 'ng2-redux';`

I have to use the require('ng2-redux') syntax else typescript complains it cannot find the module. Is there a certain requirement needed to use the "import" statement? If I can use the NgRedux import I can maybe use that in the component and as well in the `beforeEachProviders` instead of using the `@Inject` syntax.

**Comment by SethDavenport** [comment]
Hi @TobiasKrogh 

So for the 2.2.3 import error, that type of think usually happens when the typescript compiler can't locate type definitions for the library being imported.  2.2.3 now ships with type definitions: they should be in your `node modules/ng2-redux/lib/index.d.ts`.

We have it working in our webpack-based starter project: https://github.com/rangle/angular2-redux-starter/blob/master/src/index.ts#L12 

So the question is why isn't the typescript-loader for webpack picking them up in your case?

- Which webpack loader are you using for typescript? IIRC there are two or three; I've have best results with [ts-loader](https://www.npmjs.com/package/ts-loader)
- What does your `tsconfig.json` look like?
- What version of typescript are you using?

**Comment by SethDavenport** [comment]
As for the test failure - are you injecting ngRedux into your app component?  If so your unit test will likely need to supply a mock provider for it.  So something like:

```typescript
beforeEachProviders(() => [
    ApplicationRef,
    NgRedux, // or mock depending on what you're testing
    App
  ]);
```

**Comment by TobiasKrogh** [comment]
@SethDavenport thanks for the responses

the type definitions have not been installed properly. after removing node_modules/ and typings/ and reinstalling the import syntax works now and so does the import... but I get other errors and tried to peek into angular2-redux-starter to figure out what is wrong here...

as far as I can tell the `.connect` syntax is not working properly anymore with 2.2.3. I get issues when using `bindActionCreators` from redux... in https://github.com/rangle/angular2-redux-starter/commit/c89207c5767ea4f36c09c1a622984db49206f6d9 the redux typings have been removed. when adding those I see errors about `Store` having the wrong type. without them I can not use `bindActionCreators` properly as described in the README.md of `ng2-redux`

**Comment by TobiasKrogh** [comment]
I also tried to run the test against the new version and now the provider can be found when being added like:

```javascript
beforeEachProviders(() => [
  ApplicationRef,
  NgRedux, // or mock depending on what you're testing
  App
]);
```

Now I get another Error.

`Error: Cannot resolve all parameters for 'NgRedux'(?). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'NgRedux' is decorated with Injectable.`

**Comment by SethDavenport** [comment]
Hi @TobiasKrogh, thanks for your patience.

Looks like there are three different things going on in this thread.

1) A mismatch between two different versions of redux typings
2) A confusing README example on our part about the `connect` pattern
3) Your original unit test question.

__For 1:__

There are two different versions of the Redux typings in common use: the community typings from DefinitelyTyped, and the official typings from Redux 3.4.

The DefinitelyTyped typings are out of date and _should not be used_.  This is why they were removed from the Rangle.io starter as you spotted in rangle/angular2-redux-starter@c89207c

When the DT typings are removed, a properly-configured typescript setup will pull the official typings in from `node_modules/redux/index.d.ts` instead. If your project doesn't have this file, please make sure you are using Redux 3.4 and not an earlier version.

__For 2:__

I agree, the example of the `connect` pattern in our README is confusing.  I took the liberty of pushing an branch with this repo's `examples/counter` re-worked to use the `connect` API instead of the `select` API:

https://github.com/angular-redux/ng2-redux/pull/65

The specific change I had to make was to ensure that `CounterActions` has the correct type required by redux 3.4, namely `ActionCreatorMapObject`.

It turns out that the object we get from `import * as CounterActions from '../actions/CounterActions` is not in fact a regular map of functions as expected by `bindActionCreators` - it's a some module thing. In order to make it the correct type I had to move the action constants into their own file, and then `require` the action creators instead. 

TIL :)

I will update the README with an example that works better, thanks.

__ For 3:__

I'm still working on replicating your test scenario and I'll get back to you.

**Comment by SethDavenport** [comment]
Meanwhile, can you try this for your test:

```typescript
import { provider } from 'ng2-redux';

const store = // construct a mock redux store.

beforeEachProviders(() => [
  ApplicationRef,
  provider(store),
  App
]);
```

**Comment by TobiasKrogh** [comment]
Hi @SethDavenport,

**For 1:**

I can confirm that. :)

**For 2:**

Tried it - works. 👍 

**For 3:**

Since using 'redux-mock-store' was not working I constructed the store myself and though I could swear I already tried this the test is now working. What I did:

Store setup:

```javascript
import { createStore } from 'redux';
import rootReducer from '../reducers';
import { provider } from 'ng2-redux';
const store = createStore(rootReducer, {});
```

Provide:

```javascript
  // provide our implementations or mocks to the dependency injector
  beforeEachProviders(() => [
    provider(store),
    ApplicationRef,
    Styleguide
  ]);
```

**Comment by TobiasKrogh** [comment]
Many thanks for your support. I will also try to work with the `.select` syntax as recommended in the README but both variants might be helpful depending on the use case to be solved

I consider this clarified and from my perspective we can close

**Comment by TobiasKrogh** [comment]
Just as a final note: I was able to use the .select syntax and indeed it seems to fit better. I also was able to adapt my test accordingly 😄

**Comment by SethDavenport** [comment]
Happy to help.
